s1=("")
s2=("")
s3=("")
m1=("")
m2=("")
m3=("")
while s1==("")or s2==("")or s3==("")or m1==("")or m2==("") or m3==(""):
    print("-------------------------------")
    print('为了效果，尽量输入0.3到1.7的数(以1.0为基准)')
    s1=input('输入你希望的第一个表情大小：')
    s2=input('输入你希望的第二个表情大小：')
    s3=input('输入你希望的第三个表情大小：')
    print('下面的问题，0为笑脸，其他数字为苦哭脸')
    m1=input('输入你希望的第一个表情状态：')
    m2=input('输入你希望的第二个表情状态：')
    m3=input('输入你希望的第三个表情状态：')
    print("-------------------------------")
    try:
        s1=eval(s1)
        s2=eval(s2)
        s3=eval(s3)
        m1=eval(m1)
        m2=eval(m2)
        m3=eval(m3)
    except:
        s1=("")
        s2=("")
        s3=("")
        m1=("")
        m2=("")
        m3=("")
        input('数据错误，请重新输入（按回车继续）')

import turtle as t
t.speed(50)
t.setup(900,900)
t.screensize(3000,3000)

def face(x,y,s):
    t.hideturtle()
    t.penup()
    t.goto(x*s,(y-300)*s)
    t.pendown()
    t.begin_fill()
    t.pencolor('orange')
    t.fillcolor('yellow')
    t.circle(300*s)
    t.end_fill()
    t.penup()

def mouth(x,y,s,m):
    t.goto(x*s,(y-200)*s)
    t.pendown()
    t.setheading(0)
    t.pencolor('brown')
    t.pensize(3*s)
    if m==0:
        t.circle(180*s,60)
        t.circle(180*s,-120)
        t.pensize(1)
        t.penup()
    else:
        t.penup()
        t.setheading(90)
        t.forward(100*s)
        t.setheading(0)
        t.pendown()
        t.circle(-180*s,60)
        t.circle(-180*s,-120)
        t.penup()

def l_eye(x,y,s):
    t.pensize(1)
    t.goto((x-100)*s,(y+100)*s)
    t.pendown()
    t.setheading(0)
    t.fillcolor('white')
    t.begin_fill()
    t.circle(50*s)
    t.end_fill()
    t.begin_fill()
    t.color('black')
    t.circle(30*s)
    t.end_fill()
    t.penup()
    
def r_eye(x,y,s):
    t.pensize(1)
    t.goto((x+100)*s,(y+100)*s)
    t.pendown()
    t.pencolor('brown')
    t.setheading(0)
    t.fillcolor('white')
    t.begin_fill()
    t.circle(50*s)
    t.end_fill()
    t.begin_fill()
    t.color('black')
    t.circle(30*s)
    t.end_fill()

def emojy(x,y,s,m):
    face(x,y,s)
    mouth(x,y,s,m)
    l_eye(x,y,s)
    r_eye(x,y,s)

print (s1,s2,s3,m1,m2,m3)
emojy(-300,-300,s1,m1)
emojy(300,-300,s2,m2)
emojy(0,300,s3,m3)

t.exitonclick()
