a=input('你叫啥？')
print('原来你叫',a,'啊\n')
b=input('那你的性别呢？')
print('我也是',b,'的\n')
c=input('你有什么爱好呀？')
print(c,'，我也喜欢\n')
d=input('我吃过饭了，你呢？')
print('我今天吃的可好了。\n')
e=input('你多重了？')
print(e,'! 不错不错。')
