import turtle as t
t.pensize(2)
t.speed(0)
t.hideturtle()
def face(x,y):                     #脸
    t.penup()
    t.seth(0)
    t.goto(x,y)                      #脸最下端坐标
    t.pendown()
    t.color('brown','yellow')
    t.begin_fill()
    t.circle(150)
    t.end_fill()
def m(x,y):                      #嘴
    t.penup()
    t.seth(0)
    t.goto(x,y)
    t.left(90)
    t.forward(50)
    t.seth(0)
    t.pendown()
    t.color('brown','yellow')   
    t.circle(100,60)
    t.circle(100,-120)
def re(x,y):                      #右眼
    t.penup()
    t.seth(0)
    t.goto(x,y)
    t.left(90)
    t.forward(200)
    t.right(90)
    t.forward(60)
    t.pendown()
    t.color('brown','white')   
    t.begin_fill()
    t.circle(25)
    t.end_fill()
    t.color('black')   
    t.begin_fill()
    t.circle(15)
    t.end_fill()
def le(x,y):                      #左眼
    t.penup()
    t.seth(0)
    t.goto(x,y)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(60)
    t.pendown()
    t.color('brown','white')   
    t.begin_fill()
    t.circle(-25)
    t.end_fill()
    t.color('black')   
    t.begin_fill()
    t.circle(-15)
    t.end_fill()

def wz(x,y):              #整张脸
    face(x,y)
    m(x,y)
    re(x,y)
    le(x,y)
wz(200,0)
wz(200,-300)
wz(-200,0)

