import turtle as t
t.pensize(2)
t.speed(0)
t.hideturtle()
def face(x,y,z):                     #脸
    t.penup()
    t.seth(0)
    t.goto(x,y)                      #脸最下端坐标
    t.pendown()
    t.color('brown','yellow')
    t.begin_fill()
    t.circle(150*z)
    t.end_fill()
def m(x,y,z):                      #嘴
    t.penup()
    t.seth(0)
    t.goto(x,y)
    t.left(90)
    t.forward(50*z)
    t.seth(0)
    t.pendown()
    t.color('brown','yellow')   
    t.circle(100*z,60)
    t.circle(100*z,-120)
def re(x,y,z):                      #右眼
    t.penup()
    t.seth(0)
    t.goto(x,y)
    t.left(90)
    t.forward(200*z)
    t.right(90)
    t.forward(60*z)
    t.pendown()
    t.color('brown','white')   
    t.begin_fill()
    t.circle(25*z)
    t.end_fill()
    t.color('black')   
    t.begin_fill()
    t.circle(15*z)
    t.end_fill()
def le(x,y,z):                      #左眼
    t.penup()
    t.seth(0)
    t.goto(x,y)
    t.left(90)
    t.forward(200*z)
    t.left(90)
    t.forward(60*z)
    t.pendown()
    t.color('brown','white')   
    t.begin_fill()
    t.circle(-25*z)
    t.end_fill()
    t.color('black')   
    t.begin_fill()
    t.circle(-15*z)
    t.end_fill()

def wz(x,y,z):              #整张脸
    face(x,y,z)
    m(x,y,z)
    re(x,y,z)
    le(x,y,z)
wz(200,0,1)
wz(200,-300,0.5)
wz(-200,-100,1.5)

