import turtle as t

def emogi(x,y,z):
    #脸
    t.pensize(3)
    t.speed(0)
    t.penup()
    t.goto(x,y)
    t.fillcolor('yellow')
    t.begin_fill()
    t.pendown()
    t.pencolor('orange')
    t.circle(z)
    t.end_fill()

    #嘴
    t.pencolor('brown')
    t.setheading(90)
    t.penup()
    t.forward(z/3)
    t.setheading(0)
    t.pendown()
    t.circle(z*2/3,60)
    t.circle(z*2/3,-120)
    t.circle(z*2/3,60)

    #右眼
    t.penup()
    t.setheading(90)
    t.forward(z)
    t.setheading(0)
    t.forward(z/3)
    t.pendown()
    t.fillcolor('white')
    t.begin_fill()
    t.circle(z*2/15)
    t.end_fill()
    t.pencolor('black')
    t.fillcolor('black')
    t.begin_fill()
    t.circle(z/10)
    t.end_fill()

    #左眼
    t.pencolor('brown')
    t.penup()
    t.setheading(180)
    t.forward(z*2/3)
    t.pendown()
    t.fillcolor('white')
    t.begin_fill()
    t.setheading(0)
    t.circle(z*2/15)
    t.end_fill()
    t.pencolor('black')
    t.fillcolor('black')
    t.begin_fill()
    t.circle(z/10)
    t.end_fill()
    t.hideturtle()

emogi(-200,-200,100)
emogi(200,-200,125)
emogi(0,100,150)
